### ISSUE TITLE
List delta between Daisy and Bloom feature sets

### ISSUE THREAD

**Issue by willrlin** [CityOfDetroit/affordable-housing-app#39]
List out feature deltas between our front-end features and Blooms existing feature set.

- [x] Review UX design, UX research, and product documentation on feature requests
- [x] Review existing Bloom features
- [x] Add a resources section for easy access by others
- [x] Create a list of the features that are already available in Bloom
- [x] Create a list of features that we need to build
- [x] Include screenshots of features that already exist in Bloom to make sure everyone is on the same page
- [x] Propose a prioritization of the features
- [x] File github issues for the top features
- [ ] Create a list we can share with Exygy on what we plan to build
- [ ] Meet with stakeholders (UX design / research / product / HRD) to get consensus

Artifacts: 
- [x] Prioritized list of features that are not available in Bloom (https://app.box.com/file/818064858993)
- [x] Filed github issues to include in following sprints
- [ ] List of features we want to build that we can share with Exygy

**Comment by willrlin** [comment]
One thing I'd like to come out of this task that is not blocked is a doc that we can share with Exygy to say "here is where we will have to spend our time building on Bloom".

**Comment by willrlin** [comment]
Elen, what are you hoping to achieve with the "Meet with stakeholders (UX design / research / product / HRD) to get consensus" part of the task?

**Comment by elenm** [comment]
With the "meet with stakeholders" task I'm hoping to review the feature prioritization with everyone to make sure we all agree on it and I get people's feedback. I'm going to sign up for a design review slot next week and invite people to it. 

I think I'm going to break that out into a separate task along with the list to send to Exygy, because that depends on feedback / consensus from everyone.

I also had trouble running the partner portal locally, so I still need to look more closely at the Bloom partner portal capabilities after closing this task.

**Comment by willrlin** [comment]
FYI, I'm thinking that the prioritization and stakeholder buy-in should coalesce around the PRD. Feel free to get a quick once-over with Kar, but let's not try to have _this_ take the place of the PRD feature prioritization and enumeration (which is a superset of this, since Bloom would provide some of the features that are in the PRD).
