### ISSUE TITLE
Add listing data

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/affordable-housing-app#45]
Add Detroit listing data to our Bloom database instance.

Done criteria: an automated script (that can be run on-demand) to pull data from ArcGIS and write it to our Bloom DB.

**Comment by anders-schneider** [comment]
Noting Will's idea: instead of having this be a standalone script, we could create a new controller in the Bloom NestJS backend that we call whenever we want to run the import process, and then it pulls in the data from ArcGIS and then writes it to the Bloom DB using [ListingService.create](https://github.com/bloom-housing/bloom/blob/36de3ae69b2954e71d16cd7c50ebb5bd6e2fd8c7/backend/core/src/listings/listings.service.ts#L38). 

I like that this creates listings through the Bloom's existing data-access layer (since it means we wouldn't have to update the script when there are changes to the data model).

I don't like having an HTTP endpoint that triggers the whole "drop the existing listings DB and re-populate it from ArcGIS" process; that feels like we'd be adding a "reset" button to the backend API for anyone to call. At the least we'd have to really lock down the permissions on that endpoint.

A possible "best of both worlds" solution: a Python script that reads in all the data from ArcGIS and then sends multiple requests to the [ListingController.create](https://github.com/bloom-housing/bloom/blob/36de3ae69b2954e71d16cd7c50ebb5bd6e2fd8c7/backend/core/src/listings/listings.controller.ts#L49).

**Comment by anders-schneider** [comment]
As Patrick and I were looking for a place to commit the python script we're writing for this, we discovered the `backend/core/scripts` directory... and within it there's already a [`listings-importer.ts` script](https://github.com/CityOfDetroit/bloom/blob/main/backend/core/scripts/listings-importer.ts) 😅 🤦

Good news: it does basically exactly what our script does. It reads in a listing (in JSON format, from a file that's provided as a command-line argument) and does a bunch of stuff (authenticates, creates a property, formats the listing) and then uses `axios` to send POST requests to /properties and /listings. It only handles a single listing per invocation.

Bad news: I don't know how they run this such that they don't run into permissions issues. Specifically, I'm not sure how they're able to upload new properties and listings through the POST endpoints without getting caught by the AuthzGuard. There is this comment in the script:

```
NOTE: At the moment every logged in user can CRUD all entities since there are no admin role checks
```

And "at the moment" makes me wonder if they're somehow running this with a particular setup or "before" the AuthzGuard is in place. I've added questions to the doc with Exygy.

In any case, we now know how to import a bunch of listings from ArcGIS to Bloom, provided that we can relax the AuthzGuard policies so that anyone can create listings and properties. And in the interest of moving quickly (and incurring a little bit of tech debt), that may be good enough for now.

**Comment by anders-schneider** [comment]
The updated data-import scripts are now in `main`, so if anyone wants to pull in Detroit data, do the following:
1. Checkout `main` and sync it (or rebase whatever branch you're on, or somehow pull in the latest version of `main`)
2. Get the app running
3. `$ yarn ts-node scripts/import-listings-from-detroit-arcgis.ts http://localhost:3100 test@example.com:abcdef https://services2.arcgis.com/qvkbeam7Wirps6zC/ArcGIS/rest/services/Affordable_Housing_Website_data_12_20/FeatureServer/0//query`
4. Restart the app
5. Navigate to localhost:3000/listings

Note: steps 4 and 5 will take forever (O(minutes))... :expressionless:
